# Preprocesamiento de  datos Titanic

exportamos los datos

In [126]:
#librerias
import pandas as pd 
import numpy as np
from sklearn.impute import SimpleImputer

In [127]:
#conjunto de datos
prueba = pd.read_csv('test.csv')
train = pd.read_csv('train.csv')

In [128]:
prueba.size

4598

In [129]:
train.size

10692

In [130]:
#concatenamos los datos
data = pd.concat([prueba, train], ignore_index=True)

In [131]:
data.size

15708

In [132]:
data.columns


Index(['PassengerId', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp', 'Parch',
       'Ticket', 'Fare', 'Cabin', 'Embarked', 'Survived'],
      dtype='object')

In [133]:
data.head(10)

PassengerId  Pclass                                          Name     Sex  \
0          892       3                              Kelly, Mr. James    male   
1          893       3              Wilkes, Mrs. James (Ellen Needs)  female   
2          894       2                     Myles, Mr. Thomas Francis    male   
3          895       3                              Wirz, Mr. Albert    male   
4          896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female   
5          897       3                    Svensson, Mr. Johan Cervin    male   
6          898       3                          Connolly, Miss. Kate  female   
7          899       2                  Caldwell, Mr. Albert Francis    male   
8          900       3     Abrahim, Mrs. Joseph (Sophie Halaut Easu)  female   
9          901       3                       Davies, Mr. John Samuel    male   

    Age  SibSp  Parch     Ticket     Fare Cabin Embarked  Survived  
0  34.5      0      0     330911   7.8292   NaN        Q       NaN  
1  47.0      1      0     363272   7.0000   NaN        S       NaN  
2  62.0      0      0     240276   9.6875   NaN        Q       NaN  
3  27.0      0      0     315154   8.6625   NaN        S       NaN  
4  22.0      1      1    3101298  12.2875   NaN        S       NaN  
5  14.0      0      0       7538   9.2250   NaN        S       NaN  
6  30.0      0      0     330972   7.6292   NaN        Q       NaN  
7  26.0      1      1     248738  29.0000   NaN        S       NaN  
8  18.0      0      0       2657   7.2292   NaN        C       NaN  
9  21.0      2      0  A/4 48871  24.1500   NaN        S       NaN

In [134]:
data = data.drop(['Name'], axis=1)#elimina la columna nombres

## Mapeamos caracteristicas ordinales

In [135]:
sex_maping = {'male':1, 'female':0}#Masculino = 1, femenino = 0
data['Sex'] = data['Sex'].map(sex_maping)#remplaza string por entero 
Embark_maping = {'C':1, 'Q':2, 'S':3}# Embarked C = Cherbourg = 1, Q = Queenstown = 2, S = Southampton = 3 puertos
data['Embarked'] = data['Embarked'].map(Embark_maping)

In [136]:
data

PassengerId  Pclass  Sex   Age  SibSp  Parch      Ticket     Fare Cabin  \
0             892       3    1  34.5      0      0      330911   7.8292   NaN   
1             893       3    0  47.0      1      0      363272   7.0000   NaN   
2             894       2    1  62.0      0      0      240276   9.6875   NaN   
3             895       3    1  27.0      0      0      315154   8.6625   NaN   
4             896       3    0  22.0      1      1     3101298  12.2875   NaN   
...           ...     ...  ...   ...    ...    ...         ...      ...   ...   
1304          887       2    1  27.0      0      0      211536  13.0000   NaN   
1305          888       1    0  19.0      0      0      112053  30.0000   B42   
1306          889       3    0   NaN      1      2  W./C. 6607  23.4500   NaN   
1307          890       1    1  26.0      0      0      111369  30.0000  C148   
1308          891       3    1  32.0      0      0      370376   7.7500   NaN   

      Embarked  Survived  
0          2.0       NaN  
1          3.0       NaN  
2          2.0       NaN  
3          3.0       NaN  
4          3.0       NaN  
...        ...       ...  
1304       3.0       0.0  
1305       3.0       1.0  
1306       3.0       0.0  
1307       1.0       1.0  
1308       2.0       0.0  

[1309 rows x 11 columns]

In [137]:
data.Pclass.unique()#Ticket class 1 = 1st, 2 = 2nd, 3 = 3rd



array([3, 2, 1])

In [138]:
data.dtypes

PassengerId      int64
Pclass           int64
Sex              int64
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked       float64
Survived       float64
dtype: object

## Buscar valores nulos

In [139]:
data.isnull().sum()

PassengerId       0
Pclass            0
Sex               0
Age             263
SibSp             0
Parch             0
Ticket            0
Fare              1
Cabin          1014
Embarked          2
Survived        418
dtype: int64

In [140]:
data = data.drop(['Cabin'], axis=1)#elimina la columna cabina

In [141]:
data = data.dropna(subset=['Survived'])#eliminamos las filas que contienen nulos dentro de Survived

In [142]:
data = data.dropna(subset=['Embarked'])#eliminamos las filas que contienen nulos dentro de Embarked

In [143]:
data.isnull().sum()

PassengerId      0
Pclass           0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Embarked         0
Survived         0
dtype: int64

In [144]:
data.isnull().sum()

PassengerId      0
Pclass           0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Embarked         0
Survived         0
dtype: int64

In [145]:
data.head()

PassengerId  Pclass  Sex   Age  SibSp  Parch            Ticket     Fare  \
418            1       3    1  22.0      1      0         A/5 21171   7.2500   
419            2       1    0  38.0      1      0          PC 17599  71.2833   
420            3       3    0  26.0      0      0  STON/O2. 3101282   7.9250   
421            4       1    0  35.0      1      0            113803  53.1000   
422            5       3    1  35.0      0      0            373450   8.0500   

     Embarked  Survived  
418       3.0       0.0  
419       1.0       1.0  
420       3.0       1.0  
421       3.0       1.0  
422       3.0       0.0

In [146]:
data = data.drop(['Ticket'], axis=1)#elimina la columna ticket
data = data.drop(['PassengerId'], axis=1)#elimina la columna PassengerId

In [147]:
data.head(10)

Pclass  Sex   Age  SibSp  Parch     Fare  Embarked  Survived
418       3    1  22.0      1      0   7.2500       3.0       0.0
419       1    0  38.0      1      0  71.2833       1.0       1.0
420       3    0  26.0      0      0   7.9250       3.0       1.0
421       1    0  35.0      1      0  53.1000       3.0       1.0
422       3    1  35.0      0      0   8.0500       3.0       0.0
423       3    1   NaN      0      0   8.4583       2.0       0.0
424       1    1  54.0      0      0  51.8625       3.0       0.0
425       3    1   2.0      3      1  21.0750       3.0       0.0
426       3    0  27.0      0      2  11.1333       3.0       1.0
427       2    0  14.0      1      0  30.0708       1.0       1.0

### Imputamos valores ausentes en la columna Age

In [148]:
imp = SimpleImputer(missing_values=np.nan, strategy='mean')
imp = imp.fit(data.values)
imp_t = imp.transform(data.values)


In [149]:
imputad = pd.DataFrame(imp_t)
imputad.isnull().sum()

0    0
1    0
2    0
3    0
4    0
5    0
6    0
7    0
dtype: int64

In [151]:
imputad[2].values

array([22.       , 38.       , 26.       , 35.       , 35.       ,
       29.6420927, 54.       ,  2.       , 27.       , 14.       ,
        4.       , 58.       , 20.       , 39.       , 14.       ,
       55.       ,  2.       , 29.6420927, 31.       , 29.6420927,
       35.       , 34.       , 15.       , 28.       ,  8.       ,
       38.       , 29.6420927, 19.       , 29.6420927, 29.6420927,
       40.       , 29.6420927, 29.6420927, 66.       , 28.       ,
       42.       , 29.6420927, 21.       , 18.       , 14.       ,
       40.       , 27.       , 29.6420927,  3.       , 19.       ,
       29.6420927, 29.6420927, 29.6420927, 29.6420927, 18.       ,
        7.       , 21.       , 49.       , 29.       , 65.       ,
       29.6420927, 21.       , 28.5      ,  5.       , 11.       ,
       22.       , 45.       ,  4.       , 29.6420927, 29.6420927,
       29.       , 19.       , 17.       , 26.       , 32.       ,
       16.       , 21.       , 26.       , 32.       , 25.    

In [152]:
data['Age'].values

array([22.  , 38.  , 26.  , 35.  , 35.  ,   nan, 54.  ,  2.  , 27.  ,
       14.  ,  4.  , 58.  , 20.  , 39.  , 14.  , 55.  ,  2.  ,   nan,
       31.  ,   nan, 35.  , 34.  , 15.  , 28.  ,  8.  , 38.  ,   nan,
       19.  ,   nan,   nan, 40.  ,   nan,   nan, 66.  , 28.  , 42.  ,
         nan, 21.  , 18.  , 14.  , 40.  , 27.  ,   nan,  3.  , 19.  ,
         nan,   nan,   nan,   nan, 18.  ,  7.  , 21.  , 49.  , 29.  ,
       65.  ,   nan, 21.  , 28.5 ,  5.  , 11.  , 22.  , 45.  ,  4.  ,
         nan,   nan, 29.  , 19.  , 17.  , 26.  , 32.  , 16.  , 21.  ,
       26.  , 32.  , 25.  ,   nan,   nan,  0.83, 30.  , 22.  , 29.  ,
         nan, 28.  , 17.  , 33.  , 16.  ,   nan, 23.  , 24.  , 29.  ,
       20.  , 46.  , 26.  , 59.  ,   nan, 71.  , 23.  , 34.  , 34.  ,
       28.  ,   nan, 21.  , 33.  , 37.  , 28.  , 21.  ,   nan, 38.  ,
         nan, 47.  , 14.5 , 22.  , 20.  , 17.  , 21.  , 70.5 , 29.  ,
       24.  ,  2.  , 21.  ,   nan, 32.5 , 32.5 , 54.  , 12.  ,   nan,
       24.  ,   nan,

In [153]:
data['Age'] = imputad[2].values

In [154]:
data.isnull().sum()

Pclass      0
Sex         0
Age         0
SibSp       0
Parch       0
Fare        0
Embarked    0
Survived    0
dtype: int64

In [155]:
data.head(10)

Pclass  Sex        Age  SibSp  Parch     Fare  Embarked  Survived
418       3    1  22.000000      1      0   7.2500       3.0       0.0
419       1    0  38.000000      1      0  71.2833       1.0       1.0
420       3    0  26.000000      0      0   7.9250       3.0       1.0
421       1    0  35.000000      1      0  53.1000       3.0       1.0
422       3    1  35.000000      0      0   8.0500       3.0       0.0
423       3    1  29.642093      0      0   8.4583       2.0       0.0
424       1    1  54.000000      0      0  51.8625       3.0       0.0
425       3    1   2.000000      3      1  21.0750       3.0       0.0
426       3    0  27.000000      0      2  11.1333       3.0       1.0
427       2    0  14.000000      1      0  30.0708       1.0       1.0

In [158]:
data.to_parquet('dat_titanic.parquet')